gText_Birch_Welcome::
	.string "...........................................................\n"
	.string "...........................................................\p"
	.string "..........you....................get.......................\n"
	.string "............................got...to....................up.\p"
	.string "...............................on, open...............eyes.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Oh good, you're awake.\n"
	.string "You hit your head pretty hard.\p"
	.string "Who am I? It seems you hit your\l"
	.string "head harder than I thought you did.\p"
	.string "I'm your dad.\n"
	.string "Thats quite worrying.\p"
	.string "Lets see here, what do you remember\n"
	.string "about yourself?\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Let's start with something simple.$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "That's good.\n"
	.string "Do you remember your name?$"

gText_Birch_SoItsPlayer::
	.string "Are you sure it's {PLAYER}{KUN}?\p"
	.string "What about the time?$"

gText_Birch_YourePlayer::
	.string "Ah, great!\p"
	.string "It looks like you remember some things\n"
	.string "after all!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you sure your feeling\n"
	.string "feeling better?\p"
	.string "Ok. I need to head back to my\n"
	.string "gym. Be sure to tell your mom\l"
	.string "you are okay.\p"
	.string "$"
